### ISSUE TITLE
Is the simulated trajectories under different model with similar D or in other words variance in steps?

### ISSUE THREAD

**Issue by Krozard** [AnDiChallenge/ANDI_datasets#1]
It seems that different model's step variance is quite different, attached a figure I generate with similar code as the demo Jupiter notebook. alpha is 0.7 and length 200 as set in the tutorial notebook. 
![image](https://user-images.githubusercontent.com/42943190/101842124-5fa60580-3b15-11eb-909f-f2fe32a079ad.png)

![image](https://user-images.githubusercontent.com/42943190/101842147-6a609a80-3b15-11eb-8d37-041243dea1a7.png)

**Comment by gorkamunoz** [comment]
Hi krozard, sorry for the delay in the answer. Your are completely right. A way to avoid this difference is to use the function andi.normalize to the datasets before inputting them to the segmented_dataset function. This function divides the displacements over their standard deviation such that the output trajectories have a D~1.

**Comment by Krozard** [comment]
Thanks a lot for the answer!
