### ISSUE TITLE
problems with interactive-tool of andi challenge

### ISSUE THREAD

**Issue by Feng00148** [AnDiChallenge/andi_datasets#15]
Your work is wonderful, and we are also doing research on Andi Challenge. 
We find that the evaluation tool ’http://andi-challenge.org/interactive-tool/‘ given in the Andi Challenge cannot be correctly opened in the browser. It shows 'An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command'. 
Sincerely hope this tool can be used, thank you!

**Comment by gorkamunoz** [comment]
Hi! Thanks a lot for pointing out this problem, we are now aware of the problem and working on solving it, I will update asap once the interactive tool is live again!

**Comment by Feng00148** [comment]
Thank you!

**Comment by gorkamunoz** [comment]
Hi, we have a temporary solution, you can now find the tool here: https://andi-app.onrender.com/andi_app

We are aware that the app is now currently extremely slow, you have to wait ~10 secs every time you change a parameter to see the results. We are working on a better solution but we will leave this one open in the meantime.

**Comment by Feng00148** [comment]
Thanks a lot for making the tool live again!

**Comment by gorkamunoz** [comment]
Hi! The andi-app is again smoothly running at https://andi-challenge.org/interactive-tool/ .

For a better user experience, I recommend you to run it from the source here: https://andi-app.herokuapp.com/
