### ISSUE TITLE
Label Filter

### ISSUE THREAD

**Issue by raschedh** [AnDiChallenge/andi_datasets#38]
Hi, when simulating data I still obtain tracks that have less than min_seg lengths (so tracks with states that last less than 3 steps). I assume this comes from the "andi_datasets.utils_challenge.label_filter" function. This function seems to only work using the labels as an input. However, as I understand if the particle is in a multistate state (where all the labels are 2), it can still undergo a changepoint depending on whether the value of the anomolous diffusion coefficient changes (so the label function would not alter this and multistate particles can have less than 3 steps in between transitions)? All of the tracks that have this property are from the multistate states (at least for the ones I have seen).

**Comment by gorkamunoz** [comment]
Hi, when doing the filtering, we actually take into account all labels, being these alpha, D and the state. If any of these changes, a new segment is started. 

Can you give us a minimal code to reproduce the error? Also, are you working with the last version of the library (2.1.4)?

**Comment by raschedh** [comment]
Hi,

here are my steps. I created a new conda env and cloned the repo followed by pip install -e . to ensure andi 2.1.4 was installed. Then I ran the below code. It seems to be an issue when there are a lot of states (below 5). Not sure if there is a cap on this but I generated random transition matrices and diffusion/alpha values. The groups will print to screen and as can be seen some have 2 unique alpha values before changing.

from andi_datasets.datasets_challenge import challenge_phenom_dataset, _get_dic_andi2
import numpy as np 
import pandas as pd
import random 

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

dic = _get_dic_andi2(2)
dic['T'] = 500 
dic['N'] = 100

base_states = 5
D_array = np.zeros((base_states, 2))
alpha_array = np.zeros((base_states, 2))
dic['M'] = np.random.dirichlet(np.ones(base_states), size=base_states)

for i in range(base_states):
    D_array[i] = np.array([random.uniform(1,10), 0.1])
    alpha_array[i] = np.array([random.uniform(0.1,1.9), 0.1])

dic['Ds'] = D_array
dic['alphas'] = alpha_array

dfs_traj, _, _ = challenge_phenom_dataset(save_data=False, dics=[dic], return_timestep_labs=True, get_video=False)

for _, group in dfs_traj[0].groupby('traj_idx'):
    group.reset_index(drop=True, inplace=True)
    group['alpha_shifted'] = group['alpha'].shift(1)
    changepoints = group[group['alpha'] != group['alpha_shifted']].index.tolist()  
    changepoints.append(len(group))
    changepoints.pop(0)

    diff = np.diff(changepoints)
    if np.any(diff < 3):
        print(group)

**Comment by gorkamunoz** [comment]
Hi, thanks for providing your code. I have introduced a patch that solves the bug and tested it against your trajectories. Everything should run smoothly now. Feel free to pull the last changes and check that everything works.
