### ISSUE TITLE
Create submissions

### ISSUE THREAD

**Issue by FarNaz401** [AnDiChallenge/andi_datasets#41]

**Comment by gorkamunoz** [comment]
Could you include a description with your issue? Thanks!

**Comment by FarNaz401** [comment]
Hi,
Thanks, I had problem with
length_traj = df_in[df_in.traj_idx == traj_idx[idx.astype(int)]].shape[0]
line in for loop now i submit the result and i consider
for idx in np.arange(0, min(len(traj_idx_preds),len(traj_idx_true))), it
run without any error but in leaderboard didn't have any score. also i
should mention this was prediction of true data by Model 1 - Single state
diffusion.

also for Model 2 - Multiple state diffusion, it should change to:
for idx in np.arange(0, min(len(traj_idx_preds),len(traj_idx_true))):

                length_traj = df_in[df_in.traj_idx ==
traj_idx[idx.astype(int)]].shape[0]
                if (len(df_preds.changepoints[idx.astype(int)])==1):
                    prediction_traj = [idx.astype(int),
                                    Ds[idx.astype(int)]*10, # K1
                                    alphas[idx.astype(int)], # alpha1
                                    state_num[idx.astype(int)], # state1
                                    changepoints[idx.astype(int)], #
changepoint
                                    length_traj # Total length of the
trajectory
                                                                   ]
                if (len(df_preds.changepoints[idx.astype(int)])==2):
                    prediction_traj = [idx.astype(int),

Ds[df_preds.changepoints[idx.astype(int)][0]]*10, # K1

alphas[df_preds.changepoints[idx.astype(int)][0]], # alpha1

state_num[df_preds.changepoints[idx.astype(int)][0]], # state1

changepoints[df_preds.changepoints[idx.astype(int)][0]], # changepoint


Ds[df_preds.changepoints[idx.astype(int)][1]]*10, # K2

alphas[df_preds.changepoints[idx.astype(int)][1]], # alpha2

state_num[df_preds.changepoints[idx.astype(int)][1]], # state2
                                    length_traj # Total length of the
trajectory
                                               ]
                if (len(df_preds.changepoints[idx.astype(int)])==3):
                    prediction_traj = [idx.astype(int),

Ds[df_preds.changepoints[idx.astype(int)][0]]*10, # K1

alphas[df_preds.changepoints[idx.astype(int)][0]], # alpha1

state_num[df_preds.changepoints[idx.astype(int)][0]], # state1

changepoints[df_preds.changepoints[idx.astype(int)][0]], # changepoint


Ds[df_preds.changepoints[idx.astype(int)][1]]*10, # K2

alphas[df_preds.changepoints[idx.astype(int)][1]], # alpha2

state_num[df_preds.changepoints[idx.astype(int)][1]], # state2


changepoints[df_preds.changepoints[idx.astype(int)][2]], # changepoint

Ds[df_preds.changepoints[idx.astype(int)][2]]*10, # K2

alphas[df_preds.changepoints[idx.astype(int)][2]], # alpha2

state_num[df_preds.changepoints[idx.astype(int)][2]], # state2
                                    length_traj # Total length of the
trajectory
                                                                   ]

but i have error like this,
    Ds[df_preds.changepoints[idx.astype(int)][0]]*10, # K1
IndexError: index 39 is out of bounds for axis 0 with size 18

also the result for changepoints are different:
for idx in np.arange(0, far):
    if (len(df_preds.changepoints[idx.astype(int)])==2):
        print(df_preds.changepoints[idx.astype(int)][1])
12
15
23
12
10
47
47
for idx in np.arange(0, far):
    if (len(df_preds.changepoints[idx.astype(int)])==2):
        print(changepoints[df_preds.changepoints[idx.astype(int)][1]])

28
32
48
28
23
Traceback (most recent call last):
  File "<pyshell#28>", line 3, in <module>
    print(changepoints[df_preds.changepoints[idx.astype(int)][1]])
IndexError: index 47 is out of bounds for axis 0 with size 24
I'm sorry for this disordered email.

Warm regards,
Farzeneh

**Comment by FarNaz401** [comment]
Sorry, it's public, other participants can see the questions as well.
